//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBHMSEntities : DbContext
    {
        public DBHMSEntities()
            : base("name=DBHMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLBooking> TBLBookings { get; set; }
        public virtual DbSet<TBLCategory> TBLCategories { get; set; }
        public virtual DbSet<TBLRoom> TBLRooms { get; set; }
        public virtual DbSet<TBLUser> TBLUsers { get; set; }
    }
}
