//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TBLCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLCategory()
        {
            this.TBLRooms = new HashSet<TBLRoom>();
        }
    
        public int ID { get; set; }
        [DisplayName("Category Name")]
        public string Cat_Name { get; set; }
        [DisplayName("Remarks")]
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLRoom> TBLRooms { get; set; }
    }
}
